# -*- coding: utf-8 -*-
"""SVM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PdyAUSm87DnA32IjRtKrA8nEVBTTuIQh
"""

from sklearn import model_selection, svm
from sklearn.feature_extraction.text import TfidfVectorizer

documentos = [ "Los refugiados españoles fueron encontrados en París", 
              "las clases obreras no podrán", 
              "el mundo no vivirá en París y París vivirá en el mundo",
              "El horror vivido no se aguanta",
              "mejor vivir que morir",
              "así da gusto vivir",
              "ya no puedo más"]

clases = ['positivo','negativo','positivo','negativo','positivo', 'positivo' ,'negativo'] 
    
# Partición de la colección etiquetada: 30\% test-70\% entrenamiento
X_train, X_test, y_train, y_test = model_selection.train_test_split(documentos, clases, test_size=0.3, shuffle=True)
print(X_train) 
print(y_train)

vectorizer = TfidfVectorizer()
vectorizer.fit(documentos) #cálculo de los TF-IDF para todos los términos de la colección

#convertir a valores numéricos TF-IDF los datos de entramiento
X_train_Tfidf = vectorizer.transform(X_train)

SVM = svm.SVC(kernel='linear') # Definir el modelo SVM
SVM.fit(X_train_Tfidf,y_train) # Fase de entrenamiento del modelo

#convertir a valores numéricos TF-IDF los datos de testo. Fase de uso
X_test_Tfidf = vectorizer.transform(X_test)
resultado = SVM.predict(X_test_Tfidf) #uso

print(X_test)
print(resultado)

#fase de uso del modelo con un documento concreto para predecir si el documento es positivo o negativo
predictions_SVM=SVM.predict(vectorizer.transform(["no se puede con ellos"]))
print (predictions_SVM)

from sklearn.metrics import confusion_matrix

print (y_test, resultado)
tn, fp, fn, tp  = confusion_matrix(y_test, resultado).ravel()
print (tn, fp, fn, tp)

from sklearn.metrics import plot_confusion_matrix
import matplotlib.pyplot as plt

#SVM ya debe estar entrenado
disp = plot_confusion_matrix(SVM, vectorizer.transform(X_test), y_test, display_labels=["positivo", "negativo"],cmap=plt.cm.Blues) 
plt.show()
print(disp.confusion_matrix)